// Generated by CoffeeScript 1.7.1
/*
 * Refs:
 *   LDRをj、kで前後の記事、nで新しいタブで開くGreasemonkey - http://la.ma.la/blog/diary_200604261407.htm - https://gist.github.com/azu/491fa1c5050fc378c746
 *   ldrのレートを++/--できるようにするgreasemonkeyスクリプト - いぬビーム - http://d.hatena.ne.jp/kusigahama/20071107/1194447701
 *   feedeen.com for vimperator - https://gist.github.com/anekos/d0f80263bc3def842ddb
 */

(function() {
  var config =  liberator.globalVariables.ldr || {
    table: {
      nicovideo: {
        regexp: /http:\/\/www\.nicovideo\.jp\/watch\/([a-z]{2}\d+|\d+)/,
        "function": function(arg) {
          return commands.get('zenzaWatch').execute("open! " + arg);
        }
      }
    }
  };

  var rate, subCommands, switcher, w;

  w = function() {
    return content.wrappedJSObject;
  };

  rate = function() {
    return content.document.getElementById('rate_img').src.replace(/^.*(\d)\.gif$/, '$1') - 0;
  };

  switcher = function(url) {
    var k, match, v;
    match = null;
    for (k in config.table) {
      v = config.table[k];
      if (match = v.regexp.exec(url)) {
        v["function"](match[1]);
        break;
      }
    }
    if (!match) {
      if (typeof TreeStyleTabService !== "undefined" && TreeStyleTabService !== null) {
        TreeStyleTabService.readyToOpenChildTabNow(gBrowser.selectedTab);
      }
      return liberator.open(url, liberator.NEW_BACKGROUND_TAB);
    }
  };

  let unescapeEntities = function(url) {
    let div = document.createElement('div');
    div.innerHTML = url;
    return div.textContent;
  }

  subCommands = [
    new Command('next', '', function(args) {
      return w().Control.go_next();
    }), new Command('prev', '', function(args) {
      return w().Control.go_prev();
    }), new Command('open', '', function(args) {
      switcher(unescapeEntities(w().get_active_item(true).link));
      return w().Control.go_next();
    }), new Command('readitlater', '', function(args) {
      var item;
      item = w().get_active_item(true);
      liberator.plugins.readitlater.API.add(unescapeEntities(item.link), item.title, function() {
        return liberator.echo("[readitlater] added: " + item.title + " - " + item.link);
      });
      return w().Control.go_next();
    }), new Command('incrementrate', '', function(args) {
      return w().vi[rate() + 1]();
    }), new Command('decrementrate', '', function(args) {
      return w().vi[rate() - 1]();
    })
  ];

  commands.addUserCommand(['ldr'], 'reader.livedwango.com', function(args) {}, {
    subCommands: subCommands
  }, true);

}).call(this);
